### ISSUE TITLE
Compilation Failed at make command. I have grabbed the missing directory error below.

### ISSUE THREAD

**Issue by shrikant-jawalekar** [KastB/r8169#9]
make -C /lib/modules/5.4.0-53-generic/build M=$PWD modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-53-generic'
  CC [M]  /home/shrikant/r8169/r8169_aspm.o
/home/shrikant/r8169/r8169_aspm.c:28:10: fatal error: linux/pci-aspm.h: No such file or directory
 #include <linux/pci-aspm.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
scripts/Makefile.build:273: recipe for target '/home/shrikant/r8169/r8169_aspm.o' failed
make[2]: *** [/home/shrikant/r8169/r8169_aspm.o] Error 1
Makefile:1757: recipe for target '/home/shrikant/r8169' failed
make[1]: *** [/home/shrikant/r8169] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-53-generic'
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by KastB** [comment]
As mentioned in the Readme, this module is likely to be deprecated for kernels > 4.19, as the powersave feature probably comes with those kernels anyways:

https://github.com/torvalds/linux/commit/a99790bf5c7f3d68d8b01e015d3212a98ee7bd57

I would not migrate this module, unless the powersave feature does not work even for the new kernels.
Did you check 
´´´
sudo lspci -vvv | fgrep "ASPM Disabled" 
´´´
?

Otherwise I would close this issue.

Cheers
Bernd
